/* * ---------------------------------------------------------------------------
 *
 * Portions Copyright (c) 2018, ScaleFlux, Inc.
 *
 * ALL RIGHTS RESERVED. These coded instructions and program statements are
 * copyrighted works and confidential proprietary information of Scaleflux Corp.
 * They may not be modified, copied, reproduced, distributed, or disclosed to
 * third parties in any manner, medium, or form, in whole or in part.
 *
 * Scaleflux VU command definition file
 *
 * This file is automatically generated, DO NOT EDIT!!!
 *
 * ---------------------------------------------------------------------------
 */
#ifndef __VU_HANDLER_DEF_H__
#define __VU_HANDLER_DEF_H__



typedef enum {
    VU_EXEC_SUCCESS = 0,
    VU_EXEC_FAILED,
    VU_EXEC_RETRY,
} VU_STATUS_E;




// Export VU command in each VU opcode
#define OPCODE_VU                	0xCC53

// Export VU command ID defines

enum VU_0xCC53_CMD_ID_E {
	//For Group: VU config
	VUUNLOCK                                                        = 0x0U,
	VULOCK                                                          = 0x1U,
	//For Group: Mailbox config
	MSI                                                             = 0x200U,
	//For Group: System config
	VERSION                                                         = 0x02U,
	DLBOOTLOADER                                                    = 0x03U,
	CLRBOOTLOADER                                                   = 0x04U,
	DLSSS                                                           = 0x05U,
	CLRSSS                                                          = 0x06U,
	DLCFG                                                           = 0x07U,
	CFGTEST                                                         = 0x08U,
	CFGFREQ                                                         = 0x09U,
	CFGTYPE                                                         = 0x0aU,
	CFGVENDOR                                                       = 0x0bU,
	SHOWCFGINFO                                                     = 0x0cU,
	DDRINFO                                                         = 0x0dU,
	HOSTLOGDBG                                                      = 0x0eU,
	MBOXLEGACY                                                      = 0x0fU,
	MCUMBOXDRVDBG                                                   = 0x10U,
	MBOXMCTP                                                        = 0x11U,
	MBOXCLIENTDBG                                                   = 0x12U,
	INFLOGSW                                                        = 0x13U,
	//For Group: Task Scheduler
	TOP                                                             = 0x0040U,
	//For Group: Debug
	SDBCCIDBG                                                       = 0x0100U,
	DOEDEBUG                                                        = 0x0103U,
	DUMPCXLREG                                                      = 0x0104U,
	PICINIT                                                         = 0x0105U,
	MEM32                                                           = 0x0106U,
	W4                                                              = 0x0107U,
	CXLCNT                                                          = 0x0108U,
	DDRECC                                                          = 0x0109U,
	DDRGDMA                                                         = 0x010aU,
	DDRREG                                                          = 0x010bU,
	CXLDUMP                                                         = 0x010cU,
	MEM                                                             = 0x010dU,
	DDRMAPDT                                                        = 0x0116U,
	DDRWI                                                           = 0x0117U,
	DDRPR                                                           = 0x0118U,
	DDRRMWMP                                                        = 0x0119U,
	RMWMPCHK                                                        = 0x011aU,
	ECCRMWINJ                                                       = 0x011bU,
	ECCCSRINJ                                                       = 0x011cU,
	ECCINJCLR                                                       = 0x011dU,
	ECCLOG                                                          = 0x011eU,
	ECCMODE                                                         = 0x011fU,
	ECCEVTFLT                                                       = 0x0120U,
	INTRTEST                                                        = 0x0121U,
	LTSSM                                                           = 0x0122U,
	DUMPDOEREG                                                      = 0x0123U,
	CXLADBG                                                         = 0x0124U,
	BAR2DMAT                                                        = 0x0227U,
	CXLAERRINJEC                                                    = 0x0236U,
	PARITYERRINJEC                                                  = 0x0237U,
	CXLAAESCFG                                                      = 0x0125U,
	DDRTHROTTLE                                                     = 0x0126U,
	DDRCHFIX                                                        = 0x0127U,
	DDRCHGRAN                                                       = 0x0128U,
	EVTADD                                                          = 0x0129U,
	//For Group: CPMU
	CPMUREAD                                                        = 0x0222U,
	CPMUCLEAR                                                       = 0x0223U,
	CPMUSET                                                         = 0x0224U,
	CPMUFREEZE                                                      = 0x0225U,
	CPMUSTART                                                       = 0x0226U,
	//For Group: CHMU
	CHMUCTRL                                                        = 0x0230U,
	CHMUCLEAR                                                       = 0x0231U,
	CHMUPERIOD                                                      = 0x0232U,
	CHMUTHR                                                         = 0x0233U,
	CHMUREAD                                                        = 0x0234U,
	CHMUUNITSIZE                                                    = 0x0235U,
	//For Group: TIMER
	DATE                                                            = 0x0240U,
};

#ifndef MBCCI_SFX_BUILD
const char * to_string(VU_0xCC53_CMD_ID_E v);
#endif





// >>>>>   For Group: VU config

// For VU: vuUnlock
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} vuunlock;
// The VU input command data definition
typedef struct 
{
}  __packed vuunlock_input;
// The VU output command data definition
typedef struct 
{
}  __packed vuunlock_output;
// The VU command data definition
typedef union 
{
	vuunlock_input *input;
	vuunlock_output *output;
}  __packed vuunlock_data;




// For VU: vuLock
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} vulock;
// The VU input command data definition
typedef struct 
{
}  __packed vulock_input;
// The VU output command data definition
typedef struct 
{
}  __packed vulock_output;
// The VU command data definition
typedef union 
{
	vulock_input *input;
	vulock_output *output;
}  __packed vulock_data;




// >>>>>   For Group: Mailbox config

// For VU: msi
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} msi;
// The VU input command data definition
typedef struct 
{
}  __packed msi_input;
// The VU output command data definition
typedef struct 
{
	u32         type;
}  __packed msi_output;
// The VU command data definition
typedef union 
{
	msi_input *input;
	msi_output *output;
}  __packed msi_data;




// >>>>>   For Group: System config

// For VU: version
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} version;
// The VU input command data definition
typedef struct 
{
}  __packed version_input;
// The VU output command data definition
typedef struct 
{
	char        build_time[100];
	char        git_origin_info[100];
	char        git_branch_info[512];
	char        git_commit_info[100];
	char        git_author_info[100];
	char        git_time_info[100];
	char        fw_version_info[24];
	char        idfy_fw_ver[9];
	char        reserve[3051];
}  __packed version_output;
// The VU command data definition
typedef union 
{
	version_input *input;
	version_output *output;
}  __packed version_data;




// For VU: dlBootloader
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} dlbootloader;
// The VU input command data definition
typedef struct 
{
}  __packed dlbootloader_input;
// The VU output command data definition
typedef struct 
{
}  __packed dlbootloader_output;
// The VU command data definition
typedef union 
{
	dlbootloader_input *input;
	dlbootloader_output *output;
}  __packed dlbootloader_data;




// For VU: clrBootloader
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} clrbootloader;
// The VU input command data definition
typedef struct 
{
}  __packed clrbootloader_input;
// The VU output command data definition
typedef struct 
{
}  __packed clrbootloader_output;
// The VU command data definition
typedef union 
{
	clrbootloader_input *input;
	clrbootloader_output *output;
}  __packed clrbootloader_data;




// For VU: dlSSS
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} dlsss;
// The VU input command data definition
typedef struct 
{
}  __packed dlsss_input;
// The VU output command data definition
typedef struct 
{
}  __packed dlsss_output;
// The VU command data definition
typedef union 
{
	dlsss_input *input;
	dlsss_output *output;
}  __packed dlsss_data;




// For VU: clrSSS
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} clrsss;
// The VU input command data definition
typedef struct 
{
}  __packed clrsss_input;
// The VU output command data definition
typedef struct 
{
}  __packed clrsss_output;
// The VU command data definition
typedef union 
{
	clrsss_input *input;
	clrsss_output *output;
}  __packed clrsss_data;




// For VU: dlcfg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} dlcfg;
// The VU input command data definition
typedef struct 
{
}  __packed dlcfg_input;
// The VU output command data definition
typedef struct 
{
}  __packed dlcfg_output;
// The VU command data definition
typedef union 
{
	dlcfg_input *input;
	dlcfg_output *output;
}  __packed dlcfg_data;




// For VU: cfgtest
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cfgtest;
// The VU input command data definition
typedef struct 
{
}  __packed cfgtest_input;
// The VU output command data definition
typedef struct 
{
}  __packed cfgtest_output;
// The VU command data definition
typedef union 
{
	cfgtest_input *input;
	cfgtest_output *output;
}  __packed cfgtest_data;




// For VU: cfgfreq
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cfgfreq;
// The VU input command data definition
typedef struct 
{
}  __packed cfgfreq_input;
// The VU output command data definition
typedef struct 
{
}  __packed cfgfreq_output;
// The VU command data definition
typedef union 
{
	cfgfreq_input *input;
	cfgfreq_output *output;
}  __packed cfgfreq_data;




// For VU: cfgtype
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cfgtype;
// The VU input command data definition
typedef struct 
{
}  __packed cfgtype_input;
// The VU output command data definition
typedef struct 
{
}  __packed cfgtype_output;
// The VU command data definition
typedef union 
{
	cfgtype_input *input;
	cfgtype_output *output;
}  __packed cfgtype_data;




// For VU: cfgvendor
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cfgvendor;
// The VU input command data definition
typedef struct 
{
}  __packed cfgvendor_input;
// The VU output command data definition
typedef struct 
{
}  __packed cfgvendor_output;
// The VU command data definition
typedef union 
{
	cfgvendor_input *input;
	cfgvendor_output *output;
}  __packed cfgvendor_data;




// For VU: showcfginfo
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} showcfginfo;
// The VU input command data definition
typedef struct 
{
}  __packed showcfginfo_input;
// The VU output command data definition
typedef struct 
{
}  __packed showcfginfo_output;
// The VU command data definition
typedef union 
{
	showcfginfo_input *input;
	showcfginfo_output *output;
}  __packed showcfginfo_data;




// For VU: ddrinfo
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	slot;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrinfo;
// The VU input command data definition
typedef struct 
{
}  __packed ddrinfo_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrinfo_output;
// The VU command data definition
typedef union 
{
	ddrinfo_input *input;
	ddrinfo_output *output;
}  __packed ddrinfo_data;




// For VU: hostlogDbg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} hostlogdbg;
// The VU input command data definition
typedef struct 
{
}  __packed hostlogdbg_input;
// The VU output command data definition
typedef struct 
{
}  __packed hostlogdbg_output;
// The VU command data definition
typedef union 
{
	hostlogdbg_input *input;
	hostlogdbg_output *output;
}  __packed hostlogdbg_data;




// For VU: mboxlegacy
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	mbox_id;
	 u32	cmd;
	 u32	dlen;
	 u32	data;
} mboxlegacy;
// The VU input command data definition
typedef struct 
{
}  __packed mboxlegacy_input;
// The VU output command data definition
typedef struct 
{
}  __packed mboxlegacy_output;
// The VU command data definition
typedef union 
{
	mboxlegacy_input *input;
	mboxlegacy_output *output;
}  __packed mboxlegacy_data;




// For VU: mcumboxdrvdbg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	mbox_id;
	 u32	op;
	 u32	arg3;
	 u32	arg4;
} mcumboxdrvdbg;
// The VU input command data definition
typedef struct 
{
}  __packed mcumboxdrvdbg_input;
// The VU output command data definition
typedef struct 
{
}  __packed mcumboxdrvdbg_output;
// The VU command data definition
typedef union 
{
	mcumboxdrvdbg_input *input;
	mcumboxdrvdbg_output *output;
}  __packed mcumboxdrvdbg_data;




// For VU: mboxmctp
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	mbox_id;
	 u32	cmd;
	 u32	dlen;
	 u32	data;
} mboxmctp;
// The VU input command data definition
typedef struct 
{
}  __packed mboxmctp_input;
// The VU output command data definition
typedef struct 
{
}  __packed mboxmctp_output;
// The VU command data definition
typedef union 
{
	mboxmctp_input *input;
	mboxmctp_output *output;
}  __packed mboxmctp_data;




// For VU: mboxclientdbg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} mboxclientdbg;
// The VU input command data definition
typedef struct 
{
}  __packed mboxclientdbg_input;
// The VU output command data definition
typedef struct 
{
}  __packed mboxclientdbg_output;
// The VU command data definition
typedef union 
{
	mboxclientdbg_input *input;
	mboxclientdbg_output *output;
}  __packed mboxclientdbg_data;




// For VU: infLogSw
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	logsw;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} inflogsw;
// The VU input command data definition
typedef struct 
{
}  __packed inflogsw_input;
// The VU output command data definition
typedef struct 
{
}  __packed inflogsw_output;
// The VU command data definition
typedef union 
{
	inflogsw_input *input;
	inflogsw_output *output;
}  __packed inflogsw_data;




// >>>>>   For Group: Task Scheduler

// For VU: top
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} top;
// The VU input command data definition
typedef struct 
{
}  __packed top_input;
// The VU output command data definition
typedef struct 
{
}  __packed top_output;
// The VU command data definition
typedef union 
{
	top_input *input;
	top_output *output;
}  __packed top_data;




// >>>>>   For Group: Debug

// For VU: sdbCciDbg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	portid;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} sdbccidbg;
// The VU input command data definition
typedef struct 
{
}  __packed sdbccidbg_input;
// The VU output command data definition
typedef struct 
{
}  __packed sdbccidbg_output;
// The VU command data definition
typedef union 
{
	sdbccidbg_input *input;
	sdbccidbg_output *output;
}  __packed sdbccidbg_data;




// For VU: doeDebug
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} doedebug;
// The VU input command data definition
typedef struct 
{
}  __packed doedebug_input;
// The VU output command data definition
typedef struct 
{
}  __packed doedebug_output;
// The VU command data definition
typedef union 
{
	doedebug_input *input;
	doedebug_output *output;
}  __packed doedebug_data;




// For VU: dumpCxlReg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} dumpcxlreg;
// The VU input command data definition
typedef struct 
{
}  __packed dumpcxlreg_input;
// The VU output command data definition
typedef struct 
{
}  __packed dumpcxlreg_output;
// The VU command data definition
typedef union 
{
	dumpcxlreg_input *input;
	dumpcxlreg_output *output;
}  __packed dumpcxlreg_data;




// For VU: picInit
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} picinit;
// The VU input command data definition
typedef struct 
{
}  __packed picinit_input;
// The VU output command data definition
typedef struct 
{
}  __packed picinit_output;
// The VU command data definition
typedef union 
{
	picinit_input *input;
	picinit_output *output;
}  __packed picinit_data;




// For VU: mem32
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} mem32;
// The VU input command data definition
typedef struct 
{
}  __packed mem32_input;
// The VU output command data definition
typedef struct 
{
}  __packed mem32_output;
// The VU command data definition
typedef union 
{
	mem32_input *input;
	mem32_output *output;
}  __packed mem32_data;




// For VU: w4
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} w4;
// The VU input command data definition
typedef struct 
{
}  __packed w4_input;
// The VU output command data definition
typedef struct 
{
}  __packed w4_output;
// The VU command data definition
typedef union 
{
	w4_input *input;
	w4_output *output;
}  __packed w4_data;




// For VU: cxlcnt
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cxlcnt;
// The VU input command data definition
typedef struct 
{
}  __packed cxlcnt_input;
// The VU output command data definition
typedef struct 
{
}  __packed cxlcnt_output;
// The VU command data definition
typedef union 
{
	cxlcnt_input *input;
	cxlcnt_output *output;
}  __packed cxlcnt_data;




// For VU: ddrecc
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrecc;
// The VU input command data definition
typedef struct 
{
}  __packed ddrecc_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrecc_output;
// The VU command data definition
typedef union 
{
	ddrecc_input *input;
	ddrecc_output *output;
}  __packed ddrecc_data;




// For VU: ddrgdma
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrgdma;
// The VU input command data definition
typedef struct 
{
}  __packed ddrgdma_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrgdma_output;
// The VU command data definition
typedef union 
{
	ddrgdma_input *input;
	ddrgdma_output *output;
}  __packed ddrgdma_data;




// For VU: ddrreg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrreg;
// The VU input command data definition
typedef struct 
{
}  __packed ddrreg_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrreg_output;
// The VU command data definition
typedef union 
{
	ddrreg_input *input;
	ddrreg_output *output;
}  __packed ddrreg_data;




// For VU: cxldump
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cxldump;
// The VU input command data definition
typedef struct 
{
}  __packed cxldump_input;
// The VU output command data definition
typedef struct 
{
}  __packed cxldump_output;
// The VU command data definition
typedef union 
{
	cxldump_input *input;
	cxldump_output *output;
}  __packed cxldump_data;




// For VU: mem
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} mem;
// The VU input command data definition
typedef struct 
{
}  __packed mem_input;
// The VU output command data definition
typedef struct 
{
}  __packed mem_output;
// The VU command data definition
typedef union 
{
	mem_input *input;
	mem_output *output;
}  __packed mem_data;




// For VU: ddrmapdt
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrmapdt;
// The VU input command data definition
typedef struct 
{
}  __packed ddrmapdt_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrmapdt_output;
// The VU command data definition
typedef union 
{
	ddrmapdt_input *input;
	ddrmapdt_output *output;
}  __packed ddrmapdt_data;




// For VU: ddrwi
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrwi;
// The VU input command data definition
typedef struct 
{
}  __packed ddrwi_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrwi_output;
// The VU command data definition
typedef union 
{
	ddrwi_input *input;
	ddrwi_output *output;
}  __packed ddrwi_data;




// For VU: ddrpr
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrpr;
// The VU input command data definition
typedef struct 
{
}  __packed ddrpr_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrpr_output;
// The VU command data definition
typedef union 
{
	ddrpr_input *input;
	ddrpr_output *output;
}  __packed ddrpr_data;




// For VU: ddrrmwmp
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrrmwmp;
// The VU input command data definition
typedef struct 
{
}  __packed ddrrmwmp_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrrmwmp_output;
// The VU command data definition
typedef union 
{
	ddrrmwmp_input *input;
	ddrrmwmp_output *output;
}  __packed ddrrmwmp_data;




// For VU: rmwmpchk
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} rmwmpchk;
// The VU input command data definition
typedef struct 
{
}  __packed rmwmpchk_input;
// The VU output command data definition
typedef struct 
{
}  __packed rmwmpchk_output;
// The VU command data definition
typedef union 
{
	rmwmpchk_input *input;
	rmwmpchk_output *output;
}  __packed rmwmpchk_data;




// For VU: eccrmwinj
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} eccrmwinj;
// The VU input command data definition
typedef struct 
{
}  __packed eccrmwinj_input;
// The VU output command data definition
typedef struct 
{
}  __packed eccrmwinj_output;
// The VU command data definition
typedef union 
{
	eccrmwinj_input *input;
	eccrmwinj_output *output;
}  __packed eccrmwinj_data;




// For VU: ecccsrinj
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ecccsrinj;
// The VU input command data definition
typedef struct 
{
}  __packed ecccsrinj_input;
// The VU output command data definition
typedef struct 
{
}  __packed ecccsrinj_output;
// The VU command data definition
typedef union 
{
	ecccsrinj_input *input;
	ecccsrinj_output *output;
}  __packed ecccsrinj_data;




// For VU: eccinjclr
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} eccinjclr;
// The VU input command data definition
typedef struct 
{
}  __packed eccinjclr_input;
// The VU output command data definition
typedef struct 
{
}  __packed eccinjclr_output;
// The VU command data definition
typedef union 
{
	eccinjclr_input *input;
	eccinjclr_output *output;
}  __packed eccinjclr_data;




// For VU: ecclog
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ecclog;
// The VU input command data definition
typedef struct 
{
}  __packed ecclog_input;
// The VU output command data definition
typedef struct 
{
}  __packed ecclog_output;
// The VU command data definition
typedef union 
{
	ecclog_input *input;
	ecclog_output *output;
}  __packed ecclog_data;




// For VU: eccmode
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} eccmode;
// The VU input command data definition
typedef struct 
{
}  __packed eccmode_input;
// The VU output command data definition
typedef struct 
{
}  __packed eccmode_output;
// The VU command data definition
typedef union 
{
	eccmode_input *input;
	eccmode_output *output;
}  __packed eccmode_data;




// For VU: eccevtflt
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} eccevtflt;
// The VU input command data definition
typedef struct 
{
}  __packed eccevtflt_input;
// The VU output command data definition
typedef struct 
{
}  __packed eccevtflt_output;
// The VU command data definition
typedef union 
{
	eccevtflt_input *input;
	eccevtflt_output *output;
}  __packed eccevtflt_data;




// For VU: intrtest
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} intrtest;
// The VU input command data definition
typedef struct 
{
}  __packed intrtest_input;
// The VU output command data definition
typedef struct 
{
}  __packed intrtest_output;
// The VU command data definition
typedef union 
{
	intrtest_input *input;
	intrtest_output *output;
}  __packed intrtest_data;




// For VU: ltssm
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ltssm;
// The VU input command data definition
typedef struct 
{
}  __packed ltssm_input;
// The VU output command data definition
typedef struct 
{
}  __packed ltssm_output;
// The VU command data definition
typedef union 
{
	ltssm_input *input;
	ltssm_output *output;
}  __packed ltssm_data;




// For VU: dumpDoeReg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} dumpdoereg;
// The VU input command data definition
typedef struct 
{
}  __packed dumpdoereg_input;
// The VU output command data definition
typedef struct 
{
}  __packed dumpdoereg_output;
// The VU command data definition
typedef union 
{
	dumpdoereg_input *input;
	dumpdoereg_output *output;
}  __packed dumpdoereg_data;




// For VU: cxladbg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	port;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cxladbg;
// The VU input command data definition
typedef struct 
{
}  __packed cxladbg_input;
// The VU output command data definition
typedef struct 
{
}  __packed cxladbg_output;
// The VU command data definition
typedef union 
{
	cxladbg_input *input;
	cxladbg_output *output;
}  __packed cxladbg_data;




// For VU: bar2dmat
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	pattern;
	 u32	size;
	 u32	arg4;
} bar2dmat;
// The VU input command data definition
typedef struct 
{
}  __packed bar2dmat_input;
// The VU output command data definition
typedef struct 
{
}  __packed bar2dmat_output;
// The VU command data definition
typedef union 
{
	bar2dmat_input *input;
	bar2dmat_output *output;
}  __packed bar2dmat_data;




// For VU: cxlaerrinjec
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	pattern;
	 u32	size;
	 u32	arg4;
} cxlaerrinjec;
// The VU input command data definition
typedef struct 
{
}  __packed cxlaerrinjec_input;
// The VU output command data definition
typedef struct 
{
}  __packed cxlaerrinjec_output;
// The VU command data definition
typedef union 
{
	cxlaerrinjec_input *input;
	cxlaerrinjec_output *output;
}  __packed cxlaerrinjec_data;




// For VU: parityerrinjec
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	pattern;
	 u32	size;
	 u32	arg4;
} parityerrinjec;
// The VU input command data definition
typedef struct 
{
}  __packed parityerrinjec_input;
// The VU output command data definition
typedef struct 
{
}  __packed parityerrinjec_output;
// The VU command data definition
typedef union 
{
	parityerrinjec_input *input;
	parityerrinjec_output *output;
}  __packed parityerrinjec_data;




// For VU: cxlaaescfg
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cxlaaescfg;
// The VU input command data definition
typedef struct 
{
}  __packed cxlaaescfg_input;
// The VU output command data definition
typedef struct 
{
}  __packed cxlaaescfg_output;
// The VU command data definition
typedef union 
{
	cxlaaescfg_input *input;
	cxlaaescfg_output *output;
}  __packed cxlaaescfg_data;




// For VU: ddrthrottle
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrthrottle;
// The VU input command data definition
typedef struct 
{
}  __packed ddrthrottle_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrthrottle_output;
// The VU command data definition
typedef union 
{
	ddrthrottle_input *input;
	ddrthrottle_output *output;
}  __packed ddrthrottle_data;




// For VU: ddrchfix
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrchfix;
// The VU input command data definition
typedef struct 
{
}  __packed ddrchfix_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrchfix_output;
// The VU command data definition
typedef union 
{
	ddrchfix_input *input;
	ddrchfix_output *output;
}  __packed ddrchfix_data;




// For VU: ddrchgran
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} ddrchgran;
// The VU input command data definition
typedef struct 
{
}  __packed ddrchgran_input;
// The VU output command data definition
typedef struct 
{
}  __packed ddrchgran_output;
// The VU command data definition
typedef union 
{
	ddrchgran_input *input;
	ddrchgran_output *output;
}  __packed ddrchgran_data;




// For VU: evtadd
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	loglvl;
	 u32	intfmask;
	 u32	count;
	 u32	arg4;
} evtadd;
// The VU input command data definition
typedef struct 
{
}  __packed evtadd_input;
// The VU output command data definition
typedef struct 
{
}  __packed evtadd_output;
// The VU command data definition
typedef union 
{
	evtadd_input *input;
	evtadd_output *output;
}  __packed evtadd_data;




// >>>>>   For Group: CPMU

// For VU: cpmuread
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	tran;
	 u32	opcode;
	 u32	arg4;
} cpmuread;
// The VU input command data definition
typedef struct 
{
}  __packed cpmuread_input;
// The VU output command data definition
typedef struct 
{
}  __packed cpmuread_output;
// The VU command data definition
typedef union 
{
	cpmuread_input *input;
	cpmuread_output *output;
}  __packed cpmuread_data;




// For VU: cpmuclear
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} cpmuclear;
// The VU input command data definition
typedef struct 
{
}  __packed cpmuclear_input;
// The VU output command data definition
typedef struct 
{
}  __packed cpmuclear_output;
// The VU command data definition
typedef union 
{
	cpmuclear_input *input;
	cpmuclear_output *output;
}  __packed cpmuclear_data;




// For VU: cpmuset
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	tran;
	 u32	opcode;
	 u32	value;
} cpmuset;
// The VU input command data definition
typedef struct 
{
}  __packed cpmuset_input;
// The VU output command data definition
typedef struct 
{
}  __packed cpmuset_output;
// The VU command data definition
typedef union 
{
	cpmuset_input *input;
	cpmuset_output *output;
}  __packed cpmuset_data;




// For VU: cpmufreeze
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	tran;
	 u32	opcode;
	 u32	arg4;
} cpmufreeze;
// The VU input command data definition
typedef struct 
{
}  __packed cpmufreeze_input;
// The VU output command data definition
typedef struct 
{
}  __packed cpmufreeze_output;
// The VU command data definition
typedef union 
{
	cpmufreeze_input *input;
	cpmufreeze_output *output;
}  __packed cpmufreeze_data;




// For VU: cpmustart
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	tran;
	 u32	opcode;
	 u32	arg4;
} cpmustart;
// The VU input command data definition
typedef struct 
{
}  __packed cpmustart_input;
// The VU output command data definition
typedef struct 
{
}  __packed cpmustart_output;
// The VU command data definition
typedef union 
{
	cpmustart_input *input;
	cpmustart_output *output;
}  __packed cpmustart_data;




// >>>>>   For Group: CHMU

// For VU: chmuctrl
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port_inst;
	 u32	start_addr;
	 u32	fix_page_or_enable;
	 u32	down_sample;
} chmuctrl;
// The VU input command data definition
typedef struct 
{
}  __packed chmuctrl_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuctrl_output;
// The VU command data definition
typedef union 
{
	chmuctrl_input *input;
	chmuctrl_output *output;
}  __packed chmuctrl_data;




// For VU: chmuclear
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	inst;
	 u32	arg3;
	 u32	arg4;
} chmuclear;
// The VU input command data definition
typedef struct 
{
}  __packed chmuclear_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuclear_output;
// The VU command data definition
typedef union 
{
	chmuclear_input *input;
	chmuclear_output *output;
}  __packed chmuclear_data;




// For VU: chmuperiod
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	inst;
	 u32	period;
	 u32	period_mode_en;
} chmuperiod;
// The VU input command data definition
typedef struct 
{
}  __packed chmuperiod_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuperiod_output;
// The VU command data definition
typedef union 
{
	chmuperiod_input *input;
	chmuperiod_output *output;
}  __packed chmuperiod_data;




// For VU: chmuthr
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	inst;
	 u32	threshold;
	 u32	threshold_mode_en;
} chmuthr;
// The VU input command data definition
typedef struct 
{
}  __packed chmuthr_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuthr_output;
// The VU command data definition
typedef union 
{
	chmuthr_input *input;
	chmuthr_output *output;
}  __packed chmuthr_data;




// For VU: chmuread
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	inst;
	 u32	msg_sel;
	 u32	arg4;
} chmuread;
// The VU input command data definition
typedef struct 
{
}  __packed chmuread_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuread_output;
// The VU command data definition
typedef union 
{
	chmuread_input *input;
	chmuread_output *output;
}  __packed chmuread_data;




// For VU: chmuunitsize
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	port;
	 u32	inst;
	 u32	unit_size;
	 u32	arg4;
} chmuunitsize;
// The VU input command data definition
typedef struct 
{
}  __packed chmuunitsize_input;
// The VU output command data definition
typedef struct 
{
}  __packed chmuunitsize_output;
// The VU command data definition
typedef union 
{
	chmuunitsize_input *input;
	chmuunitsize_output *output;
}  __packed chmuunitsize_data;




// >>>>>   For Group: TIMER

// For VU: date
// The VU command parameter definition, dw10~14 and cqe[0/1] definition
typedef struct
{
	 u32	vuCmdId;
	 u32	status;
	 u32	in_sz;
	 u32	out_sz;
	 u32	arg1;
	 u32	arg2;
	 u32	arg3;
	 u32	arg4;
} date;
// The VU input command data definition
typedef struct 
{
}  __packed date_input;
// The VU output command data definition
typedef struct 
{
}  __packed date_output;
// The VU command data definition
typedef union 
{
	date_input *input;
	date_output *output;
}  __packed date_data;







#ifndef MBCCI_SFX_BUILD
//
//
//For command dispatch function of this OPCODE: OPCODE_VU
//
VU_STATUS_E opcode_vu_0xcc53_dispatch_cmd(VU_CMD_HDR_T *hdr, CCI_DATA_S *mb);




//
//
//For OPCODE: OPCODE_VU
//

// >>>>>   For Group: VU config
// for VU: vuUnlock
VU_STATUS_E vu_handler_vuunlock(vector<string> *pargs __unused, vuunlock *param __unused, vuunlock_data *pdata __unused);
// for VU: vuLock
VU_STATUS_E vu_handler_vulock(vector<string> *pargs __unused, vulock *param __unused, vulock_data *pdata __unused);

// >>>>>   For Group: Mailbox config
// for VU: msi
VU_STATUS_E vu_handler_msi(vector<string> *pargs __unused, msi *param __unused, msi_data *pdata __unused);

// >>>>>   For Group: System config
// for VU: version
VU_STATUS_E vu_handler_version(vector<string> *pargs __unused, version *param __unused, version_data *pdata __unused);
// for VU: dlBootloader
VU_STATUS_E vu_handler_dlbootloader(vector<string> *pargs __unused, dlbootloader *param __unused, dlbootloader_data *pdata __unused);
// for VU: clrBootloader
VU_STATUS_E vu_handler_clrbootloader(vector<string> *pargs __unused, clrbootloader *param __unused, clrbootloader_data *pdata __unused);
// for VU: dlSSS
VU_STATUS_E vu_handler_dlsss(vector<string> *pargs __unused, dlsss *param __unused, dlsss_data *pdata __unused);
// for VU: clrSSS
VU_STATUS_E vu_handler_clrsss(vector<string> *pargs __unused, clrsss *param __unused, clrsss_data *pdata __unused);
// for VU: dlcfg
VU_STATUS_E vu_handler_dlcfg(vector<string> *pargs __unused, dlcfg *param __unused, dlcfg_data *pdata __unused);
// for VU: cfgtest
VU_STATUS_E vu_handler_cfgtest(vector<string> *pargs __unused, cfgtest *param __unused, cfgtest_data *pdata __unused);
// for VU: cfgfreq
VU_STATUS_E vu_handler_cfgfreq(vector<string> *pargs __unused, cfgfreq *param __unused, cfgfreq_data *pdata __unused);
// for VU: cfgtype
VU_STATUS_E vu_handler_cfgtype(vector<string> *pargs __unused, cfgtype *param __unused, cfgtype_data *pdata __unused);
// for VU: cfgvendor
VU_STATUS_E vu_handler_cfgvendor(vector<string> *pargs __unused, cfgvendor *param __unused, cfgvendor_data *pdata __unused);
// for VU: showcfginfo
VU_STATUS_E vu_handler_showcfginfo(vector<string> *pargs __unused, showcfginfo *param __unused, showcfginfo_data *pdata __unused);
// for VU: ddrinfo
VU_STATUS_E vu_handler_ddrinfo(vector<string> *pargs __unused, ddrinfo *param __unused, ddrinfo_data *pdata __unused);
// for VU: hostlogDbg
VU_STATUS_E vu_handler_hostlogdbg(vector<string> *pargs __unused, hostlogdbg *param __unused, hostlogdbg_data *pdata __unused);
// for VU: mboxlegacy
VU_STATUS_E vu_handler_mboxlegacy(vector<string> *pargs __unused, mboxlegacy *param __unused, mboxlegacy_data *pdata __unused);
// for VU: mcumboxdrvdbg
VU_STATUS_E vu_handler_mcumboxdrvdbg(vector<string> *pargs __unused, mcumboxdrvdbg *param __unused, mcumboxdrvdbg_data *pdata __unused);
// for VU: mboxmctp
VU_STATUS_E vu_handler_mboxmctp(vector<string> *pargs __unused, mboxmctp *param __unused, mboxmctp_data *pdata __unused);
// for VU: mboxclientdbg
VU_STATUS_E vu_handler_mboxclientdbg(vector<string> *pargs __unused, mboxclientdbg *param __unused, mboxclientdbg_data *pdata __unused);
// for VU: infLogSw
VU_STATUS_E vu_handler_inflogsw(vector<string> *pargs __unused, inflogsw *param __unused, inflogsw_data *pdata __unused);

// >>>>>   For Group: Task Scheduler
// for VU: top
VU_STATUS_E vu_handler_top(vector<string> *pargs __unused, top *param __unused, top_data *pdata __unused);

// >>>>>   For Group: Debug
// for VU: sdbCciDbg
VU_STATUS_E vu_handler_sdbccidbg(vector<string> *pargs __unused, sdbccidbg *param __unused, sdbccidbg_data *pdata __unused);
// for VU: doeDebug
VU_STATUS_E vu_handler_doedebug(vector<string> *pargs __unused, doedebug *param __unused, doedebug_data *pdata __unused);
// for VU: dumpCxlReg
VU_STATUS_E vu_handler_dumpcxlreg(vector<string> *pargs __unused, dumpcxlreg *param __unused, dumpcxlreg_data *pdata __unused);
// for VU: picInit
VU_STATUS_E vu_handler_picinit(vector<string> *pargs __unused, picinit *param __unused, picinit_data *pdata __unused);
// for VU: mem32
VU_STATUS_E vu_handler_mem32(vector<string> *pargs __unused, mem32 *param __unused, mem32_data *pdata __unused);
// for VU: w4
VU_STATUS_E vu_handler_w4(vector<string> *pargs __unused, w4 *param __unused, w4_data *pdata __unused);
// for VU: cxlcnt
VU_STATUS_E vu_handler_cxlcnt(vector<string> *pargs __unused, cxlcnt *param __unused, cxlcnt_data *pdata __unused);
// for VU: ddrecc
VU_STATUS_E vu_handler_ddrecc(vector<string> *pargs __unused, ddrecc *param __unused, ddrecc_data *pdata __unused);
// for VU: ddrgdma
VU_STATUS_E vu_handler_ddrgdma(vector<string> *pargs __unused, ddrgdma *param __unused, ddrgdma_data *pdata __unused);
// for VU: ddrreg
VU_STATUS_E vu_handler_ddrreg(vector<string> *pargs __unused, ddrreg *param __unused, ddrreg_data *pdata __unused);
// for VU: cxldump
VU_STATUS_E vu_handler_cxldump(vector<string> *pargs __unused, cxldump *param __unused, cxldump_data *pdata __unused);
// for VU: mem
VU_STATUS_E vu_handler_mem(vector<string> *pargs __unused, mem *param __unused, mem_data *pdata __unused);
// for VU: ddrmapdt
VU_STATUS_E vu_handler_ddrmapdt(vector<string> *pargs __unused, ddrmapdt *param __unused, ddrmapdt_data *pdata __unused);
// for VU: ddrwi
VU_STATUS_E vu_handler_ddrwi(vector<string> *pargs __unused, ddrwi *param __unused, ddrwi_data *pdata __unused);
// for VU: ddrpr
VU_STATUS_E vu_handler_ddrpr(vector<string> *pargs __unused, ddrpr *param __unused, ddrpr_data *pdata __unused);
// for VU: ddrrmwmp
VU_STATUS_E vu_handler_ddrrmwmp(vector<string> *pargs __unused, ddrrmwmp *param __unused, ddrrmwmp_data *pdata __unused);
// for VU: rmwmpchk
VU_STATUS_E vu_handler_rmwmpchk(vector<string> *pargs __unused, rmwmpchk *param __unused, rmwmpchk_data *pdata __unused);
// for VU: eccrmwinj
VU_STATUS_E vu_handler_eccrmwinj(vector<string> *pargs __unused, eccrmwinj *param __unused, eccrmwinj_data *pdata __unused);
// for VU: ecccsrinj
VU_STATUS_E vu_handler_ecccsrinj(vector<string> *pargs __unused, ecccsrinj *param __unused, ecccsrinj_data *pdata __unused);
// for VU: eccinjclr
VU_STATUS_E vu_handler_eccinjclr(vector<string> *pargs __unused, eccinjclr *param __unused, eccinjclr_data *pdata __unused);
// for VU: ecclog
VU_STATUS_E vu_handler_ecclog(vector<string> *pargs __unused, ecclog *param __unused, ecclog_data *pdata __unused);
// for VU: eccmode
VU_STATUS_E vu_handler_eccmode(vector<string> *pargs __unused, eccmode *param __unused, eccmode_data *pdata __unused);
// for VU: eccevtflt
VU_STATUS_E vu_handler_eccevtflt(vector<string> *pargs __unused, eccevtflt *param __unused, eccevtflt_data *pdata __unused);
// for VU: intrtest
VU_STATUS_E vu_handler_intrtest(vector<string> *pargs __unused, intrtest *param __unused, intrtest_data *pdata __unused);
// for VU: ltssm
VU_STATUS_E vu_handler_ltssm(vector<string> *pargs __unused, ltssm *param __unused, ltssm_data *pdata __unused);
// for VU: dumpDoeReg
VU_STATUS_E vu_handler_dumpdoereg(vector<string> *pargs __unused, dumpdoereg *param __unused, dumpdoereg_data *pdata __unused);
// for VU: cxladbg
VU_STATUS_E vu_handler_cxladbg(vector<string> *pargs __unused, cxladbg *param __unused, cxladbg_data *pdata __unused);
// for VU: bar2dmat
VU_STATUS_E vu_handler_bar2dmat(vector<string> *pargs __unused, bar2dmat *param __unused, bar2dmat_data *pdata __unused);
// for VU: cxlaerrinjec
VU_STATUS_E vu_handler_cxlaerrinjec(vector<string> *pargs __unused, cxlaerrinjec *param __unused, cxlaerrinjec_data *pdata __unused);
// for VU: parityerrinjec
VU_STATUS_E vu_handler_parityerrinjec(vector<string> *pargs __unused, parityerrinjec *param __unused, parityerrinjec_data *pdata __unused);
// for VU: cxlaaescfg
VU_STATUS_E vu_handler_cxlaaescfg(vector<string> *pargs __unused, cxlaaescfg *param __unused, cxlaaescfg_data *pdata __unused);
// for VU: ddrthrottle
VU_STATUS_E vu_handler_ddrthrottle(vector<string> *pargs __unused, ddrthrottle *param __unused, ddrthrottle_data *pdata __unused);
// for VU: ddrchfix
VU_STATUS_E vu_handler_ddrchfix(vector<string> *pargs __unused, ddrchfix *param __unused, ddrchfix_data *pdata __unused);
// for VU: ddrchgran
VU_STATUS_E vu_handler_ddrchgran(vector<string> *pargs __unused, ddrchgran *param __unused, ddrchgran_data *pdata __unused);
// for VU: evtadd
VU_STATUS_E vu_handler_evtadd(vector<string> *pargs __unused, evtadd *param __unused, evtadd_data *pdata __unused);

// >>>>>   For Group: CPMU
// for VU: cpmuread
VU_STATUS_E vu_handler_cpmuread(vector<string> *pargs __unused, cpmuread *param __unused, cpmuread_data *pdata __unused);
// for VU: cpmuclear
VU_STATUS_E vu_handler_cpmuclear(vector<string> *pargs __unused, cpmuclear *param __unused, cpmuclear_data *pdata __unused);
// for VU: cpmuset
VU_STATUS_E vu_handler_cpmuset(vector<string> *pargs __unused, cpmuset *param __unused, cpmuset_data *pdata __unused);
// for VU: cpmufreeze
VU_STATUS_E vu_handler_cpmufreeze(vector<string> *pargs __unused, cpmufreeze *param __unused, cpmufreeze_data *pdata __unused);
// for VU: cpmustart
VU_STATUS_E vu_handler_cpmustart(vector<string> *pargs __unused, cpmustart *param __unused, cpmustart_data *pdata __unused);

// >>>>>   For Group: CHMU
// for VU: chmuctrl
VU_STATUS_E vu_handler_chmuctrl(vector<string> *pargs __unused, chmuctrl *param __unused, chmuctrl_data *pdata __unused);
// for VU: chmuclear
VU_STATUS_E vu_handler_chmuclear(vector<string> *pargs __unused, chmuclear *param __unused, chmuclear_data *pdata __unused);
// for VU: chmuperiod
VU_STATUS_E vu_handler_chmuperiod(vector<string> *pargs __unused, chmuperiod *param __unused, chmuperiod_data *pdata __unused);
// for VU: chmuthr
VU_STATUS_E vu_handler_chmuthr(vector<string> *pargs __unused, chmuthr *param __unused, chmuthr_data *pdata __unused);
// for VU: chmuread
VU_STATUS_E vu_handler_chmuread(vector<string> *pargs __unused, chmuread *param __unused, chmuread_data *pdata __unused);
// for VU: chmuunitsize
VU_STATUS_E vu_handler_chmuunitsize(vector<string> *pargs __unused, chmuunitsize *param __unused, chmuunitsize_data *pdata __unused);

// >>>>>   For Group: TIMER
// for VU: date
VU_STATUS_E vu_handler_date(vector<string> *pargs __unused, date *param __unused, date_data *pdata __unused);

// dispatch VU function
VU_STATUS_E dispatch_uart_cmd(vector<string> *pargs);

#endif

#endif

